name: Cypress Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  cypress-run:
    name: Cypress E2E tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          STORE_URL: ${{ secrets.SHOPIFY_STORE_URL }}
          SHOPIFY_PASSWORD: ${{ secrets.SHOPIFY_PASSWORD }}
          GB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
